config/routes.rb
Rails.application.routes.draw do

#  resources :standups
   mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  default_url_options :host => "localhost"

  devise_for :users,controllers: {registrations: 'registrations'}
  resource :accounts
  resources :teams,
path: 't'
get 't/new', to: 'teams#new'
get 't/:id/edit', to: 'teams#edit'
get 't/:id/s', to: 'teams#standups', as: 'team_standups'
get 't/:id/s/(:date)', to: 'teams#standups', as: 'team_standups_by_date'
get 't/:id/(:date)', to: 'teams#show'

get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
resources :standups, path: 's' # except: [:new, :edit]

  get 'user/me', to: 'users#me', as: 'my_settings'
patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
get 'user/password', to: 'users#password', as: 'my_password'
patch 'user/update_password',to:'users#update_password',as:'my_update_password'
scope 'account', as: 'account' do
resources :users
end
  get 'activity/mine'
  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  scope 'account', as: 'account' do
resources :users do
member do
get 's', to: 'users#standups', as: 'standups'
end
end
resources :plans, only: [:index, :show], controller: 'accounts/plans'
end


require "sidekiq/web"
require 'sidekiq/cron/web'
Sidekiq::Web.use Rack::Auth::Basic do |username, password|
ActiveSupport::SecurityUtils.secure_compare(
::Digest::SHA256.hexdigest(username),
::Digest::SHA256.hexdigest(ENV["SK_USER"])
) &
ActiveSupport::SecurityUtils.secure_compare(
::Digest::SHA256.hexdigest(password),
::Digest::SHA256.hexdigest(ENV["SK_PASS"])
)
end if Rails.env.production?
mount Sidekiq::Web, at: "/sidekiq"

# mount using default path: /email_processor
mount_griddler

mount StripeEvent::Engine, at: '/billing/events' 
resources :cards, only: [:create]
resources :plans, only: [:index, :show]
resources :subscriptions, only: [:create, :destroy]
resources :billing, only: [:index] do
collection do
get 'change_card'
end
end

  root 'activity#mine'


end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  
 authorize_resource :class => "ActivityController"
  def mine
    @standups = current_user.standups 
    @standups = @standups.includes(:dids, :todos, :blockers).references(:tasks).order('standup_date DESC')  
    @standups = @standups.page params[:page]
  
  end

  def feed
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/views/activity/feed.html.slim
h1 Activity#feed
p Find me in app/views/activity/feed.html.slim

app/views/activity/mine.html.slim
.content-header
  h2 My Activity
.content
  - @standups.each_slice(3) do |standups|
    .row
      - standups.each do |standup|
       -cache standup do
          .col-sm-4
            .box.box-primary
              .box-header.with-border
                .box-tools.pull-right
                  =link_to edit_standup_path(date: standup.standup_date) do
                    .fa.fa-wrench
                h3.box-title= standup.standup_date
              .box-body
                h4
                  | Dids
                  ul.todo-list
                    - standup.dids.each do |did|
                      - cache did do
                        li= did.title
                h4
                  | Todos
                  ul.todo-list
                    - standup.todos.each do |todo|
                      - cache todo do
                        li = todo.title
                h4
                  | Blockers
                  ul.todo-list
                    - standup.blockers.each do |blocker|
                      - cache blocker do
                        li = blocker.title
  .row
    .col-sm-12
      = paginate @standups