config/routes.rb
Rails.application.routes.draw do

#  resources :standups
   mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  default_url_options :host => "localhost"

  devise_for :users,controllers: {registrations: 'registrations'}
  resource :accounts
  resources :teams,
path: 't'
get 't/new', to: 'teams#new'
get 't/:id/edit', to: 'teams#edit'
get 't/:id/s', to: 'teams#standups', as: 'team_standups'
get 't/:id/s/(:date)', to: 'teams#standups', as: 'team_standups_by_date'
get 't/:id/(:date)', to: 'teams#show'

get 's/new/(:date)', to: 'standups#new', as: 'new_standup'
get 's/edit/(:date)', to: 'standups#edit', as: 'edit_standup'
resources :standups, path: 's' # except: [:new, :edit]

  get 'user/me', to: 'users#me', as: 'my_settings'
patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
get 'user/password', to: 'users#password', as: 'my_password'
patch 'user/update_password',to:'users#update_password',as:'my_update_password'
scope 'account', as: 'account' do
resources :users
end
  get 'activity/mine'
  get 'activity/feed'

  get 'dates/:date', to: 'dates#update', as: 'update_date'

  scope 'account', as: 'account' do
resources :users do
member do
get 's', to: 'users#standups', as: 'standups'
end
end
resources :plans, only: [:index, :show], controller: 'accounts/plans'
end


require "sidekiq/web"
require 'sidekiq/cron/web'
Sidekiq::Web.use Rack::Auth::Basic do |username, password|
ActiveSupport::SecurityUtils.secure_compare(
::Digest::SHA256.hexdigest(username),
::Digest::SHA256.hexdigest(ENV["SK_USER"])
) &
ActiveSupport::SecurityUtils.secure_compare(
::Digest::SHA256.hexdigest(password),
::Digest::SHA256.hexdigest(ENV["SK_PASS"])
)
end if Rails.env.production?
mount Sidekiq::Web, at: "/sidekiq"

# mount using default path: /email_processor
mount_griddler

mount StripeEvent::Engine, at: '/billing/events' 
resources :cards, only: [:create]
resources :plans, only: [:index, :show]
resources :subscriptions, only: [:create, :destroy]
resources :billing, only: [:index] do
collection do
get 'change_card'
end
end

  root 'activity#mine'


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)


    user ||= User.new # guest user (not logged in)
if user.has_role?(:user, user.account || Account.new)
can [:me, :password, :update_me, :update_password], User
can [:feed, :mine], ActivityController
cannot :manage, Account
elsif user.has_role?(:admin, user.account || Account.new) #is an admin
can :manage, :all
else
can [:new, :create], Account
end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord

  resourcify
  has_many :users
  has_one :subscription
  validates :name, presence: true
  has_many :teams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blocker.rb
class Blocker < Task

end

app/models/did.rb
class Did < Task

end

app/models/plan.rb
class Plan
def self.plans
@plans ||= PLANS.keys.map { |k| PLANS[k] }
end
def self.all
plans.map { |plan| OpenStruct.new(plan) }
end
def self.where(args)
conditions = args.map do |arg_key, arg_val|
proc { |plan| plan[arg_key] == arg_val }
end
local_plans = plans.select { |plan| conditions.all? { |c| c.call(plan) } }
local_plans.flatten.map { |plan| OpenStruct.new(plan) }
end
def self.find(stripe_id)
plan = plans.find { |p| p[:stripe_id] == stripe_id }
OpenStruct.new(plan)
end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/standup.rb
class Standup < ApplicationRecord

  include Friendlyable

  belongs_to :user
validates :user, presence:true

has_many :task_memberships
has_many :tasks, through: :task_memberships
has_many :dids,
-> { where(type: 'Did') },
through: :task_memberships,
source: :task
accepts_nested_attributes_for :dids,
reject_if: :all_blank,
allow_destroy: true
has_many :todos,
-> { where(type: 'Todo') },
through: :task_memberships,
source: :task
accepts_nested_attributes_for :todos,
reject_if: :all_blank,
allow_destroy: true
has_many :blockers,
-> { where(type: 'Blocker') },
through: :task_memberships,
source: :task
accepts_nested_attributes_for :blockers,
reject_if: :all_blank,
allow_destroy: true
end

app/models/stripe_webhook.rb
class StripeWebhook < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
end

app/models/task.rb
class Task < ApplicationRecord

validates :title, presence:true
validates :type, presence: true
has_many :task_memberships
has_many :standups, through: :task_memberships
end

app/models/task_membership.rb
class TaskMembership < ApplicationRecord
  belongs_to :task
  belongs_to :standup
end

app/models/team.rb
class Team < ApplicationRecord

include Friendlyable

  belongs_to :account
  belongs_to :account
validates :account, presence: true
validates :timezone, presence: true
validates :name, presence: true
has_many :team_memberships
has_many :users, through: :team_memberships
has_many :days, class_name: 'DaysOfTheWeekMembership'
accepts_nested_attributes_for :days
end

app/models/team_membership.rb
class TeamMembership < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/todo.rb
class Todo < Task

end

app/models/user.rb
class User < ApplicationRecord

  include Friendlyable
  rolify
  attr_accessor :role
  belongs_to :account, optional: true
  has_many :standups
has_many :team_memberships
has_many :teams, through: :team_memberships
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block alert-fixed">
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/standups_helper.rb
module StandupsHelper

  def notification_standups(user)
user
.teams
.flat_map do |t|
t.users.flat_map do |u|
u.standups.order(created_at: :desc).limit(10)
end
end
.sort_by(&:created_at)
.reverse[0..9]
end
end

app/views/layouts/navigation/_footer.slim
footer.main-footer class="#{'full-footer' unless @team.present? && !@team.id.nil?}"
  .pull-right.hidden-xs
    | Anything you want
  strong
    | Copyright © 2016
    a href="#"  Company
  | All rights reserved.

app/views/layouts/navigation/_header.slim
header.main-header
  a.logo href="/"
    | Standup App
  /! Header Navbar: style can be found in header.less
  nav.navbar.navbar-static-top role="navigation"
    .pull-left
      a.logo href="/t"
        | Teams
      a.logo href="/s"
        | Standups
        =link_to "out", destroy_user_session_path, merhod: :delete,class:"logo"
      a.logo.standup href="/s/new/#{Date.today.iso8601}"
        | Submit a Standup
    /! Navbar Right Menu
    .navbar-custom-menu
      ul.nav.navbar-nav
        /! Notifications: style can be found in dropdown.less
        li.dropdown.notifications-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-bell-o
            span.label.label-warning style="display:none"
              | NEW
          ul.dropdown-menu#notification-container
            = render partial: 'layouts/navigation/notifications',\
              locals:\
               {notification_standups: notification_standups(current_user)}
        /! User Account: style can be found in dropdown.less
        li.dropdown.user.user-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            img.user-image{
              alt=("User Image")
              src="#{gravatar_image_url(current_user.email, size: 25, secure:true )}"
            }
            span.hidden-xs = current_user.name
          ul.dropdown-menu
            li.header= current_user.name
            li.divider
            li
              a href="/user/me"
                | Profile
            - if current_user.has_role? :admin, current_account
              li
                a href="/account/users"
                  | Settings
              li
               /= link_to 'Billing', billing_index_path
            li.divider
            li
              = link_to(destroy_user_session_path, method: :delete) do
                i.fa.fa-sign-out
                | Log out

app/views/layouts/navigation/_layout.slim
= render "layouts/navigation/header"
= render "layouts/navigation/sidebar"

app/views/layouts/navigation/_notifications.html.slim
li.header
  = "Last #{notification_standups.size} notifications"
  li
    ul.menu
      - notification_standups.each do |standup|
        li
          a
            = "#{standup.user.name} just added a standup for #{standup.standup_date}"

app/views/layouts/navigation/_notifications.slim
li.header
  = "Last #{notification_standups.size} notifications"
  li
    ul.menu
      - notification_standups.each do |standup|
        li
          a
            = "#{standup.user.name} just added a standup for #{standup.standup_date}"

app/views/layouts/navigation/_sidebar.slim
- if @team.present? && !@team.id.nil?
  .main-sidebar
    .sidebar
      .user-panel
        .pull-left.image
          h3.header-circ
              = @team&.name[0]&.upcase
        .pull-left.info style="vertical-align: middle; margin-top: 5px;"
          p= @team.name
        .clearfix
        span.hidden-xs.description
          p= @team.description
      ul.sidebar-menu
        li.header Overview
        li
          = link_to team_path(@team),\
            {id: "edit_#{@team.hash_id}_sidebar"} do
              .fa.fa-dashboard
              span Details
        li
          = link_to edit_team_path(@team),\
            {id: "edit_#{@team.hash_id}_sidebar"} do
              .fa.fa-cog
              span Settings
      ul.sidebar-menu
        li.header Standups
        li
          a href="/t/#{@team.hash_id}/s"
            .fa.fa-child
            span View

app/views/payments/invoice_payment_succeeded/email.html.slim
= @message

app/views/payments/invoice_payment_succeeded/email.text.slim
= @message

app/views/payments/invoice_upcoming/email.html.slim
= @message

app/views/payments/invoice_upcoming/email.text.slim
= @message

app/views/shared/_model_errors.slim
- if model.errors.any?
  .alert.alert-error
    button.close data-dismiss="alert" type="button" x
    ul
      - model.errors.full_messages.each do |msg|
        li= msg